#!/bin/ksh
#  JOB card cerated for running METPlus-based Global enesmble verifications
#   By Binbin Zhou, IMSG@EMC/NCEP
#   Feb 2, 2022
#
set -xa
#######################################################
#######################################################

export cycle=${cycle:-t00z}

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

export COMIN=${COMIN:-$(compath.py  $envir/com/$NET/$evs_ver)}/stats/$COMPONENT/$MODELNAME.$VDATE
export COMOUT=${COMOUT:-$(compath.py -o $envir/com/$NET/${evs_ver})}/$STEP/$COMPONENT/$RUN.$VDATE
mkdir $COMOUT

export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs_gens.${evs_ver}}
export EXECevs=$HOMEevs/exec
export PARMevs=$HOMEevs/parm
export USHevs=$HOMEevs/ush
export SCRIPTerf=$HOMEevs/scripts
export FIXevs=${FIXevs:-/lfs/h1/ops/prod/packages/evs.${evs_ver}/fix}
export DATA=${DATA:-${DATAROOT}/${jobid:?}}
mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

# Run setpdy and initialize PDY variables
setpdy.sh
. $DATA/PDY

if [ $RUN = atmos ] ; then
  export INITDATE=${INITDATE:-$PDYm2}
fi

sh $HOMEevs/scripts/${COMPONENT}/${STEP}/exevs_${COMPONENT}_${RUN}_${VERIF_CASE}_${STEP}.sh

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date

